#!/bin/sh

# Run PHP Code Beautifier
if [ -f vendor/bin/phpcbf ]; then
  echo "Running PHP Code Beautifier..."
  vendor/bin/phpcbf --standard=phpcs.xml -ps .
fi

# Run PHP Code Sniffer
if [ -f vendor/bin/phpcs ]; then
  echo "Running PHP Code Sniffer aaa..."
  vendor/bin/phpcs --standard=phpcs.xml -ps .
  if [ $? -ne 0 ]; then
    echo "Error: PHP Code Sniffer found issues. Please fix them before committing."
    exit 1
  fi
else
  echo "PHP Code Sniffer not found. Skipping code sniffing."
fi

echo "phpcbf completed successfully."

# Run NPM Build
if [ -f package.json ]; then
  echo "Running npm build process..."
  npm run build
  if [ $? -ne 0 ]; then
    echo "Error: npm run build failed."
    exit 1
  fi
  echo "npm build process completed successfully."
else
  echo "No package.json found. Skipping npm build process."
fi

# Add generated build files to the commit
echo "Adding build files to the commit..."
git add -u  # This stages the changes of any tracked files
git add build/
git add src/
git add *.php

echo "Pre-commit hook completed successfully. Proceeding with the commit..."
exit 0
