#!/bin/sh

# Run PHP Code Beautifier
if [ -f vendor/bin/phpcbf ]; then
  echo "Running PHP Code Beautifier..."
  vendor/bin/phpcbf -ps .
fi

echo "phpcbf completed successfully."

# Run NPM Build
if [ -f package.json ]; then
  echo "Running npm build process..."
  npm run build
  if [ $? -ne 0 ]; then
    echo "Error: npm run build failed."
    exit 1
  fi
  echo "npm build process completed successfully."
else
  echo "No package.json found. Skipping npm build process."
fi

# Add generated build files to the commit
echo "Adding build files to the commit..."
git add -u  # This stages the changes of any tracked files
git add build/
git add src/
git add *.php


echo "Pre-commit hook completed successfully. Proceeding with the commit..."
exit 0
