include:
  - project: 'wpify/gitlab-ci-templates'
    ref: master
    file:
      - 'jobs/node.yml'

assets:
  stage: .pre
  image: node:20
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 1 week
  before_script:
    - npm ci --force
  script:
    - NODE_ENV=production npm run build


.git:
  image: alpine:latest
  variables:
    GIT_URL: gitlab.com
    GIT_REPO: wpify/custom-fields
    CLONE_PATH: /root/custom-fields
  before_script:
    - apk update
    - apk add bash git rsync
    - git config --global user.email "${GIT_EMAIL}"
    - git config --global user.name "${GIT_NAME}"
    - git clone "https://$GIT_USER:$GIT_ACCESS_TOKEN@$GIT_URL/$GIT_REPO.git" "$CLONE_PATH"
  only:
    - master

deploy_master:
  stage: deploy
  extends: .git
  needs:
    - assets
  script: |
    # extract latest message
    message=$(git log -1 --pretty=%B)

    # remove /build/ from .gitignore file
    sed -i '/\/build\//d' ./.gitignore

    # copy changes to deploy path
    rsync -a --delete --exclude '.git' $CI_PROJECT_DIR/ $CLONE_PATH/

    # go to the cloned repository
    cd $CLONE_PATH

    # Get current status
    git status --porcelain

    # Commit and push changes
    git add .
    git commit -am "$message"
    git push --force origin HEAD:$CI_COMMIT_REF_NAME
  only:
    - master

deploy_tag:
  stage: deploy
  extends: .git
  script: |
    # go to cloned repository
    cd $CLONE_PATH

    # create and push the tag
    git tag "$CI_COMMIT_REF_NAME"
    git push --tags
  only:
    - tags
